package edu.brown.cs.student.main;

/**
 * The insert_bf command inserts elements into a bloom filter
 * Run insert_bf [element]
 *
 *  Insert_bf outputs the Bloom filter’s bitset after setting the proper bits
 *  based on the k hashes of the input element
 *
 * It implements the REPL and Command interface, so it must add itself to the
 * commands hashMap and implement execute.
 *
 * @author kkmarcus
 */
public class InsertBF implements Command {

  /**
   * Constructor must add itself to REPL hashmap containing command name and classes
   */
  InsertBF() {
    String commandName = "insert_bf";
    this.addCommands(commandName, this);
  }

  /**
   * execute must check to see if a bloom filter has been created yet, otherwise
   * throw error
   *
   * @param args (array of strings)
   */
  public void execute(String[] args) {
    BloomFilterBuilder bloomFilter =
        (BloomFilterBuilder) REPL.getCommandObject(
            "create_bf"); // grab bf generated by create_bf, if it exists
    if (bloomFilter == null) { // if it is null, no bf has been generated yet
      System.out.println("ERROR: No Bloom Filter exists, run create_bf <r> <n>");
    } else if (args.length != 2) { // check the correct amount of args
      System.out.println("ERROR: Missing or too many args, enter insert_bf <element>");
    } else {
      String element = args[1]; // get element
      bloomFilter.add(element); // call add method to insert element into bloom filter
      String bitset = bloomFilter.toBinaryString();
      System.out.println(bitset);
    }
  }
}

